[package]
name = "nand-to-browser"
version = "0.1.0"
edition = "2021"
authors = ["Felix Schoeller <felix.schoeller@protonmail.com>"]
description = "A Nand to Tetris Emulator implementation that can run in the browser"
license-file = "LICENSE"

# wasm packages must be cdylib
[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
# dependencies for the web ui
wasm-bindgen = "0.2"

# logs panics with console.err which is nice for debugging
console_error_panic_hook = { version = "0.1.7", optional = true }

[profile.release]
# optimize for small code size to reduce the download time on first page load
opt-level = "s"
