[package]
name = "nand-to-browser"
version = "0.1.0"
edition = "2021"
authors = ["Felix Schoeller <felix.schoeller@protonmail.com>"]
description = "A Nand to Tetris Emulator implementation that can run in the browser"

[dependencies]
